# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to register Compute Managers with NSX Appliance
#
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - deploy_nsx_cluster_vars.yml
  tasks:
    - name: Add NSX License
      nsxt_licenses:
          hostname: "{{ nsx_node1.mgmt_ip }}"
          username: "{{ nsx_username }}"
          password: "{{ nsx_password }}"
          validate_certs: "{{ validate_certs }}"
          license_key: "{{ item.license_key }}"
          state: "{{ state }}"
      with_items:
        - "{{nsxt_licenses}}"
